
package essalud.gob.pe.portal.incapacidad.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OSPEVirtual", targetNamespace = "http://controller.ospe.essalud.gob.pe/", wsdlLocation = "http://10.0.29.34:8080/WSOspeVirtual/OSPEVirtual?wsdl")
public class OSPEVirtual_Service
    extends Service
{

    private final static URL OSPEVIRTUAL_WSDL_LOCATION;
    private final static WebServiceException OSPEVIRTUAL_EXCEPTION;
    private final static QName OSPEVIRTUAL_QNAME = new QName("http://controller.ospe.essalud.gob.pe/", "OSPEVirtual");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.0.29.34:8080/WSOspeVirtual/OSPEVirtual?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OSPEVIRTUAL_WSDL_LOCATION = url;
        OSPEVIRTUAL_EXCEPTION = e;
    }

    public OSPEVirtual_Service() {
        super(__getWsdlLocation(), OSPEVIRTUAL_QNAME);
    }

    public OSPEVirtual_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), OSPEVIRTUAL_QNAME, features);
    }

    public OSPEVirtual_Service(URL wsdlLocation) {
        super(wsdlLocation, OSPEVIRTUAL_QNAME);
    }

    public OSPEVirtual_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OSPEVIRTUAL_QNAME, features);
    }

    public OSPEVirtual_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OSPEVirtual_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OSPEVirtual
     */
    @WebEndpoint(name = "OSPEVirtualPort")
    public OSPEVirtual getOSPEVirtualPort() {
        return super.getPort(new QName("http://controller.ospe.essalud.gob.pe/", "OSPEVirtualPort"), OSPEVirtual.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OSPEVirtual
     */
    @WebEndpoint(name = "OSPEVirtualPort")
    public OSPEVirtual getOSPEVirtualPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.ospe.essalud.gob.pe/", "OSPEVirtualPort"), OSPEVirtual.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OSPEVIRTUAL_EXCEPTION!= null) {
            throw OSPEVIRTUAL_EXCEPTION;
        }
        return OSPEVIRTUAL_WSDL_LOCATION;
    }

}
