
package gob.pe.essalud.appincapacidad.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OSPEVirtual", targetNamespace = "http://controller.ospe.essalud.gob.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OSPEVirtual {


    /**
     * 
     * @param pass
     * @param nrdoc
     * @param fecinicio
     * @param tpdoc
     * @param fecfin
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFamilyBond")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetFamilyBond", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.GetFamilyBond")
    @ResponseWrapper(localName = "GetFamilyBondResponse", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.GetFamilyBondResponse")
    public String getFamilyBond(
        @WebParam(name = "tpdoc", targetNamespace = "")
        String tpdoc,
        @WebParam(name = "nrdoc", targetNamespace = "")
        String nrdoc,
        @WebParam(name = "fecinicio", targetNamespace = "")
        String fecinicio,
        @WebParam(name = "fecfin", targetNamespace = "")
        String fecfin,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param codUsuario
     * @param nroExpediente
     * @param ipUsuario
     * @param pass
     * @param terUsuario
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendReactivation", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.SendReactivation")
    @ResponseWrapper(localName = "sendReactivationResponse", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.SendReactivationResponse")
    public String sendReactivation(
        @WebParam(name = "nroExpediente", targetNamespace = "")
        String nroExpediente,
        @WebParam(name = "codUsuario", targetNamespace = "")
        String codUsuario,
        @WebParam(name = "terUsuario", targetNamespace = "")
        String terUsuario,
        @WebParam(name = "ipUsuario", targetNamespace = "")
        String ipUsuario,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param tpSubsidio
     * @param pass
     * @param nrdoc
     * @param tpdoc
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCITT")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetCITT", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.GetCITT")
    @ResponseWrapper(localName = "GetCITTResponse", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.GetCITTResponse")
    public String getCITT(
        @WebParam(name = "tpdoc", targetNamespace = "")
        String tpdoc,
        @WebParam(name = "nrdoc", targetNamespace = "")
        String nrdoc,
        @WebParam(name = "tpSubsidio", targetNamespace = "")
        String tpSubsidio,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param pass
     * @param nrdoc
     * @param tpdoc
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmploymentRelationship", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.GetEmploymentRelationship")
    @ResponseWrapper(localName = "getEmploymentRelationshipResponse", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.GetEmploymentRelationshipResponse")
    public String getEmploymentRelationship(
        @WebParam(name = "tpdoc", targetNamespace = "")
        String tpdoc,
        @WebParam(name = "nrdoc", targetNamespace = "")
        String nrdoc,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param pass
     * @param user
     * @param nrruc
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTaxpayer")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetTaxpayer", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.GetTaxpayer")
    @ResponseWrapper(localName = "GetTaxpayerResponse", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.GetTaxpayerResponse")
    public String getTaxpayer(
        @WebParam(name = "nrruc", targetNamespace = "")
        String nrruc,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param pass
     * @param nrdoc
     * @param tpcitt
     * @param tpdoc
     * @param state
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ReportInability")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ReportInability", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.ReportInability")
    @ResponseWrapper(localName = "ReportInabilityResponse", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.ReportInabilityResponse")
    public String reportInability(
        @WebParam(name = "tpdoc", targetNamespace = "")
        String tpdoc,
        @WebParam(name = "nrdoc", targetNamespace = "")
        String nrdoc,
        @WebParam(name = "tpcitt", targetNamespace = "")
        String tpcitt,
        @WebParam(name = "state", targetNamespace = "")
        String state,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param codUsuario
     * @param pass
     * @param ideSolicitud
     * @param tpDocTitularSia
     * @param user
     * @param nrDocBeneficiario
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendBackOfficeInability", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.SendBackOfficeInability")
    @ResponseWrapper(localName = "sendBackOfficeInabilityResponse", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.SendBackOfficeInabilityResponse")
    public String sendBackOfficeInability(
        @WebParam(name = "ideSolicitud", targetNamespace = "")
        int ideSolicitud,
        @WebParam(name = "tpDocTitularSia", targetNamespace = "")
        String tpDocTitularSia,
        @WebParam(name = "nrDocBeneficiario", targetNamespace = "")
        String nrDocBeneficiario,
        @WebParam(name = "codUsuario", targetNamespace = "")
        String codUsuario,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param tpSubsidio
     * @param fecIniSol
     * @param pass
     * @param nrdoc
     * @param fecFinSol
     * @param tpdoc
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get20Days", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.Get20Days")
    @ResponseWrapper(localName = "get20DaysResponse", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.Get20DaysResponse")
    public String get20Days(
        @WebParam(name = "tpdoc", targetNamespace = "")
        String tpdoc,
        @WebParam(name = "nrdoc", targetNamespace = "")
        String nrdoc,
        @WebParam(name = "tpSubsidio", targetNamespace = "")
        String tpSubsidio,
        @WebParam(name = "fecIniSol", targetNamespace = "")
        String fecIniSol,
        @WebParam(name = "fecFinSol", targetNamespace = "")
        String fecFinSol,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param pass
     * @param codSolicitud
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reportLactancia", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.ReportLactancia")
    @ResponseWrapper(localName = "reportLactanciaResponse", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.ReportLactanciaResponse")
    public String reportLactancia(
        @WebParam(name = "codSolicitud", targetNamespace = "")
        String codSolicitud,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param pass
     * @param json
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendInability", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.SendInability")
    @ResponseWrapper(localName = "sendInabilityResponse", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.SendInabilityResponse")
    public String sendInability(
        @WebParam(name = "json", targetNamespace = "")
        String json,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param pass
     * @param citt
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyPaymentMaternity", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.VerifyPaymentMaternity")
    @ResponseWrapper(localName = "verifyPaymentMaternityResponse", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.VerifyPaymentMaternityResponse")
    public String verifyPaymentMaternity(
        @WebParam(name = "citt", targetNamespace = "")
        String citt,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param pass
     * @param nrdoc
     * @param tpdoc
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetInsuredData")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetInsuredData", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.GetInsuredData")
    @ResponseWrapper(localName = "GetInsuredDataResponse", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.GetInsuredDataResponse")
    public String getInsuredData(
        @WebParam(name = "tpdoc", targetNamespace = "")
        String tpdoc,
        @WebParam(name = "nrdoc", targetNamespace = "")
        String nrdoc,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param pass
     * @param nrdoc
     * @param tpdoc
     * @param state
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReactivationInsured", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.GetReactivationInsured")
    @ResponseWrapper(localName = "getReactivationInsuredResponse", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.GetReactivationInsuredResponse")
    public String getReactivationInsured(
        @WebParam(name = "tpdoc", targetNamespace = "")
        String tpdoc,
        @WebParam(name = "nrdoc", targetNamespace = "")
        String nrdoc,
        @WebParam(name = "state", targetNamespace = "")
        String state,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param opcion
     * @param pass
     * @param nrdoc
     * @param tpdoc
     * @param codSolicitud
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateStatusInability", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.UpdateStatusInability")
    @ResponseWrapper(localName = "updateStatusInabilityResponse", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.UpdateStatusInabilityResponse")
    public String updateStatusInability(
        @WebParam(name = "codSolicitud", targetNamespace = "")
        String codSolicitud,
        @WebParam(name = "opcion", targetNamespace = "")
        String opcion,
        @WebParam(name = "tpdoc", targetNamespace = "")
        String tpdoc,
        @WebParam(name = "nrdoc", targetNamespace = "")
        String nrdoc,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param pass
     * @param user
     * @param lactancia
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarLactancia", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.InsertarLactancia")
    @ResponseWrapper(localName = "insertarLactanciaResponse", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.InsertarLactanciaResponse")
    public String insertarLactancia(
        @WebParam(name = "lactancia", targetNamespace = "")
        SubLactanciaBean lactancia,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param pass
     * @param maternity
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerMaternityApplication", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.RegisterMaternityApplication")
    @ResponseWrapper(localName = "registerMaternityApplicationResponse", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.RegisterMaternityApplicationResponse")
    public String registerMaternityApplication(
        @WebParam(name = "Maternity", targetNamespace = "")
        MaternityBean maternity,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param pass
     * @param state
     * @param user
     * @param nrruc
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReactivationEmployer", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.GetReactivationEmployer")
    @ResponseWrapper(localName = "getReactivationEmployerResponse", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.GetReactivationEmployerResponse")
    public String getReactivationEmployer(
        @WebParam(name = "nrruc", targetNamespace = "")
        String nrruc,
        @WebParam(name = "state", targetNamespace = "")
        String state,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param pass
     * @param nrdoc
     * @param tpdoc
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetInsuredReniec")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetInsuredReniec", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.GetInsuredReniec")
    @ResponseWrapper(localName = "GetInsuredReniecResponse", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.GetInsuredReniecResponse")
    public String getInsuredReniec(
        @WebParam(name = "tpdoc", targetNamespace = "")
        String tpdoc,
        @WebParam(name = "nrdoc", targetNamespace = "")
        String nrdoc,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param fecIniSubs
     * @param nrDocTitular
     * @param pass
     * @param fecFinSubs
     * @param tpPago
     * @param tpDocTitular
     * @param rucEmpleador
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendReimbursementPayment", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.SendReimbursementPayment")
    @ResponseWrapper(localName = "sendReimbursementPaymentResponse", targetNamespace = "http://controller.ospe.essalud.gob.pe/", className = "gob.pe.essalud.appincapacidad.wsdl.SendReimbursementPaymentResponse")
    public String sendReimbursementPayment(
        @WebParam(name = "tpDocTitular", targetNamespace = "")
        String tpDocTitular,
        @WebParam(name = "nrDocTitular", targetNamespace = "")
        String nrDocTitular,
        @WebParam(name = "rucEmpleador", targetNamespace = "")
        String rucEmpleador,
        @WebParam(name = "fecIniSubs", targetNamespace = "")
        String fecIniSubs,
        @WebParam(name = "fecFinSubs", targetNamespace = "")
        String fecFinSubs,
        @WebParam(name = "tpPago", targetNamespace = "")
        String tpPago,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

}
