#auth-server: http://localhost:8080/authoriza
auth-server: http://10.0.29.34:8080/ovauthoriza
server:
  servlet:
    session:
      cookie:
        name: UISESSION
security:
  oauth2:
    client:
      client-id: appincapacidad
      client-secret: essalud2019
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      user-info-uri: ${auth-server}/user/login
spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
  messages:
    basename: messages
  application:
    name: appincapacidad
  jmx:
    default-domain: appincapacidad
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 3MB
      max-request-size: 4MB
      enabled: true
endpoints:
enabled: false